name: env
channels:
    - blaze
    - menpo
    - conda-forge
dependencies:
- click=6.7
- flake8=3.5.0
- jupyter=1.0.0
- jupyterthemes=0.18.3
- matplotlib=2.1.2
- numpy=1.14.1
- pandas=0.22.0
- pep8=1.7.1
- pytest=3.3.2
- pytest-cov=2.5.1
- python-dotenv=0.8.2
- python=3.6
- scikit-learn=0.19.1
- scipy==1.0.0
- seaborn=0.8.1
- pip:
     - blinker==1.4
     - pytest-pythonpath==0.7.1
     - sklearn-pandas==1.6.0
     - tables==3.4.2
     - munch==2.3.1
     - imbalanced-learn==0.3.3
     -e git+https://github.com/nicotom/yaer.git#egg=yaer
